[paths]
ffmpeg = "ffmpeg"
slippi_playback = "/storage/slippi/squashfs-root/usr/bin/dolphin-emu"
ssbm_iso = "/storage/melee/melee.iso"

[dolphin]
backend = "Software Renderer"
resolution = "480p"
bitrate = 3500

[ffmpeg]
volume = 25

[runtime]
parallel = 0
youtubify_names = false
